/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ball.gltf 
Author: Jay Salton (https://sketchfab.com/jaysalton)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pokemon-poke-ball-9f63803d93714eadaa869c23cee0581d
Title: Pokémon Poké Ball
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';
export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/models/ball.gltf')
  useFrame(() => {
    if (group.current) {
      group.current.rotation.y += 0.001; 
      group.current.rotation.x += 0.01;
      // group.current.rotation.z += 0.01;
    }
  });
  
  return (
    <group ref={group} {...props} dispose={null}>

      <mesh geometry={nodes.polySurface11_phong2_0.geometry} material={materials.phong2} />
      <mesh geometry={nodes.polySurface11_phong1_0.geometry} material={materials.phong1} />
      <mesh geometry={nodes.polySurface11_lambert1_0.geometry} material={materials.lambert1} />
    </group>
  )
}

useGLTF.preload('/models/ball.gltf')
